### ISSUE TITLE
Error when running cli.py

### ISSUE THREAD

**Issue by maddingl** [flother/htmltab#3]
When I run cli.py, I get the following error:

```
$ python cli.py
Traceback (most recent call last):
  File "cli.py", line 6, in <module>
    import csv
  File "/usr/lib/python3.8/csv.py", line 6, in <module>
    import re
  File "/usr/lib/python3.8/re.py", line 122, in <module>
    import enum
  File "/usr/lib/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
  File "[path to types.py]", line 1, in <module>
    from click.types import ParamType
  File "$HOME/.local/lib/python3.8/site-packages/click/__init__.py", line 7, in <module>
    from .core import Argument
  File "$HOME/.local/lib/python3.8/site-packages/click/core.py", line 2, in <module>
    import inspect
  File "/usr/lib/python3.8/inspect.py", line 35, in <module>
    import dis
  File "/usr/lib/python3.8/dis.py", line 16, in <module>
    _have_code = (types.MethodType, types.FunctionType, types.CodeType,
AttributeError: partially initialized module 'types' has no attribute 'MethodType' (most likely due to a circular import)
```

**Comment by flother** [comment]
Hi @maddingl,

This is because you're trying to run htmltab from inside its own package, and [`types.py`](https://github.com/flother/htmltab/blob/master/htmltab/types.py) conflicts with [Python's `types` library](https://docs.python.org/3/library/types.html). There are also other things that stop you using htmltab like this. I came across several others while trying it out (e.g. [relative imports](https://github.com/flother/htmltab/blob/2483b354ae33ad420bfd42d3cadc7253b0480c90/htmltab/utils.py#L10)), so it's safe to safe that htmltab isn't designed to work like this.

If you want to run it from a local copy of the repo, you should be able to run `python3 setup.py develop` and then an `htmltab` command will be available in your virtualenv. And if you don't need the repo, then running it as in https://github.com/flother/htmltab/issues/2#issuecomment-617087310 will work too.
